export interface ChildRouteItem {
  slug: string;
  name: string;
  shortDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  overview: string;
  keyFeatures: string[];
  technologies: string[];
  useCases: string[];
  relatedServices?: string[];
  relatedSolutions?: string[];
}

export interface ServiceCategory {
  slug: string;
  name: string;
  tag: string;
  iconName: string;
  shortDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  overview: string;
  keyFeatures: string[];
  technologies: string[];
  childRoutes: ChildRouteItem[];
  relatedSolutions?: string[];
}

export interface IndustrySolution {
  slug: string;
  name: string;
  badge: string;
  shortDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  overview: string;
  challengesSolved: string[];
  coreCapabilities: string[];
  technologies: string[];
  connectedServices: { name: string; href: string }[];
}

export interface FinanceToolItem {
  slug: string;
  name: string;
  badge: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  formulaDescription: string;
  keyBenefits: string[];
}

// ─── 6 PRIMARY SERVICES & 30 CHILD ROUTES ─────────────────────────────────────

export const SERVICES_CONFIG: ServiceCategory[] = [
  {
    slug: "website-development",
    name: "Website Development",
    tag: "Web & UX",
    iconName: "Globe",
    shortDescription: "High-performance, SEO-optimized digital web experiences built with Next.js, React, and modern web frameworks.",
    heroTitle: "High-Performance Website Development",
    heroSubtitle: "Engineered for sub-second page loads, accessible UI/UX, and maximum conversion rates across all screen sizes.",
    overview: "We engineer modern websites that combine lightning-fast frontend architectures with sleek interactive design systems. From business portfolios to high-converting eCommerce storefronts, every website is built with clean semantic code, strict SEO foundations, and enterprise-grade security.",
    keyFeatures: [
      "Sub-second page speeds with Next.js & Server-Side Rendering (SSR)",
      "Strict SEO architecture, Open Graph, schema.org JSON-LD & meta tags",
      "Adaptive dark/light theme systems with fluid CSS styling",
      "Enterprise security headers, SSL/TLS, and OWASP compliance",
      "Integrated CMS support and dynamic markdown/headless content",
      "100% mobile-first responsive design audited for Lighthouse 95+ scores",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "HTML5/CSS3", "Framer Motion", "Vercel", "Node.js"],
    relatedSolutions: ["ecommerce", "startup-mvp", "business-management"],
    childRoutes: [
      {
        slug: "business-websites",
        name: "Business Websites",
        shortDescription: "Modern corporate and commercial websites establishing credible digital brand authority.",
        heroTitle: "Custom Business Website Development",
        heroSubtitle: "Establish industry credibility with modern, accessible, and ultra-fast business web platforms.",
        overview: "Our business website engineering delivers polished, interactive digital platforms that turn organic visitors into qualified business inquiries. Every build is tailored to your brand's unique market position.",
        keyFeatures: ["Custom brand-aligned design system", "Integrated lead capture & analytics", "Speed optimization & CDN routing", "Accessible WCAG-compliant UI"],
        technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
        useCases: ["Mid-market enterprises", "Professional service firms", "B2B service providers", "Agencies"],
        relatedServices: ["web-application-development", "business-automation"],
        relatedSolutions: ["business-management", "startup-mvp"],
      },
      {
        slug: "corporate-websites",
        name: "Corporate Websites",
        shortDescription: "Enterprise-grade digital portals with multi-region localization, investor relations, and security.",
        heroTitle: "Enterprise Corporate Web Platforms",
        heroSubtitle: "Scalable, secure, and multi-region web infrastructure for growing corporate organizations.",
        overview: "We engineer resilient corporate web portals designed for high-traffic environments, multi-stakeholder governance, investor transparency, and global accessibility compliance.",
        keyFeatures: ["Multi-region localization & CDN caching", "Strict role governance & audit logging", "Compliance-ready privacy & cookie architectures", "High-concurrency uptime SLA"],
        technologies: ["Next.js", "React", "Node.js", "TypeScript", "PostgreSQL"],
        useCases: ["Public corporations", "Financial holding companies", "Conglomerates", "Global brands"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["fintech", "business-management"],
      },
      {
        slug: "ecommerce-websites",
        name: "eCommerce Websites",
        shortDescription: "High-converting online storefronts with seamless checkout flows and inventory management.",
        heroTitle: "High-Converting eCommerce Platforms",
        heroSubtitle: "Engineered for frictionless checkouts, real-time inventory sync, and maximum buyer conversions.",
        overview: "From custom headless storefronts to scalable multi-vendor marketplaces, we build performant eCommerce solutions with lightning-fast catalog search, dynamic cart state management, and reliable payment integrations.",
        keyFeatures: ["Instant sub-second product filtering & search", "Secure payment gateway integrations (Stripe, Razorpay, Cashfree)", "Automated invoice & order notification pipelines", "Abandoned cart recovery hooks"],
        technologies: ["Next.js", "React", "Node.js", "PostgreSQL", "Tailwind CSS"],
        useCases: ["Direct-to-consumer (D2C) brands", "B2B wholesale portals", "Digital product marketplaces", "Subscription commerce"],
        relatedServices: ["web-application-development", "backend-development"],
        relatedSolutions: ["ecommerce", "fintech"],
      },
      {
        slug: "landing-pages",
        name: "High-Converting Landing Pages",
        shortDescription: "Performance-engineered landing pages built for marketing campaigns and product launches.",
        heroTitle: "High-Converting Landing Page Engineering",
        heroSubtitle: "Maximized for ad-campaign ROI, A/B testing agility, and rapid customer acquisition.",
        overview: "We design and engineer bespoke campaign landing pages optimized for maximum conversion velocity, instant zero-lag loading, and clean analytical attribution.",
        keyFeatures: ["Zero-bloat bundle size (<80KB initial load)", "Integrated Google Ads & Meta Pixel tracking", "Interactive product demo previews", "Dynamic UTM parameter routing"],
        technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
        useCases: ["Product launch campaigns", "SaaS acquisition funnels", "PPC ad campaigns", "Event registrations"],
        relatedServices: ["business-automation", "website-development"],
        relatedSolutions: ["startup-mvp", "fintech"],
      },
      {
        slug: "seo-websites",
        name: "SEO-First Websites",
        shortDescription: "Search-engine-first web architecture engineered for organic ranking and topical authority.",
        heroTitle: "SEO-First Architecture & Web Engineering",
        heroSubtitle: "Engineered from the ground up for indexability, Core Web Vitals, and organic search domination.",
        overview: "Our SEO-first web engineering ensures clean HTML5 semantic hierarchy, server-rendered dynamic XML sitemaps, JSON-LD structured schema data, and optimal crawl budget efficiency.",
        keyFeatures: ["Automated Schema.org JSON-LD generation", "Perfect Core Web Vitals (LCP < 1.2s, CLS 0)", "Canonical URL management & Open Graph cards", "Dynamic programmatic SEO routing"],
        technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
        useCases: ["Content publishers", "Aggregators & directories", "High-growth startups", "Local SEO brands"],
        relatedServices: ["website-development", "backend-development"],
        relatedSolutions: ["startup-mvp", "business-management"],
      },
    ],
  },
  {
    slug: "web-application-development",
    name: "Web Application Development",
    tag: "Full-Stack",
    iconName: "Code2",
    shortDescription: "Scalable SaaS platforms, custom dashboards, enterprise web portals, and complex cloud applications.",
    heroTitle: "Scalable Web Application Development",
    heroSubtitle: "Engineered for high concurrent users, complex business logic, and real-time interactive workflows.",
    overview: "We build enterprise-grade web applications with modern decoupled architectures, reactive client state, secure JWT session governance, and optimized PostgreSQL databases.",
    keyFeatures: [
      "Full-stack TypeScript architecture with React, Next.js & Fastify",
      "Role-Based Access Control (RBAC) & enterprise authentication",
      "Real-time data streaming & WebSocket notification layers",
      "Optimized relational SQL database querying with Prisma & PostgreSQL",
      "Modular micro-frontend & reusable component design systems",
      "Automated CI/CD pipelines with zero-downtime rolling deployments",
    ],
    technologies: ["React", "Next.js", "Node.js", "TypeScript", "Fastify", "PostgreSQL", "Prisma", "Redis", "Docker"],
    relatedSolutions: ["fintech", "loan-finance-platforms", "business-management", "startup-mvp"],
    childRoutes: [
      {
        slug: "saas-development",
        name: "SaaS Platform Development",
        shortDescription: "Multi-tenant Software-as-a-Service architectures with recurring billing and user isolation.",
        heroTitle: "Multi-Tenant SaaS Platform Development",
        heroSubtitle: "Build, launch, and scale high-concurrency SaaS platforms with clean multi-tenant architectures.",
        overview: "We build scalable SaaS products from zero to production, incorporating multi-tenant database isolation, automated recurring billing, organization seat management, and usage analytics.",
        keyFeatures: ["Multi-tenant tenant routing & data isolation", "Stripe & billing cycle automation", "Team workspaces & role permissions", "Telemetry & usage tracking APIs"],
        technologies: ["Next.js", "Fastify", "PostgreSQL", "Prisma", "Redis"],
        useCases: ["B2B SaaS products", "Analytics dashboards", "Collaboration software", "Subscription platforms"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["startup-mvp", "fintech"],
      },
      {
        slug: "crm-development",
        name: "Custom CRM Development",
        shortDescription: "Tailored customer relationship management systems aligned with your sales pipelines.",
        heroTitle: "Custom CRM System Engineering",
        heroSubtitle: "Manage leads, track deals, and automate client communication with zero off-the-shelf limitations.",
        overview: "Eliminate expensive per-seat software licenses with custom CRM applications engineered specifically for your company's sales stages, lead assignment rules, and interaction timelines.",
        keyFeatures: ["Visual drag-and-drop deal pipelines", "Automated lead ingestion & executive distribution", "WhatsApp & email communication logs", "Real-time revenue forecasting reports"],
        technologies: ["React", "Next.js", "Node.js", "PostgreSQL", "Tailwind CSS"],
        useCases: ["Financial advisory firms", "Real estate brokers", "B2B sales teams", "Consultancies"],
        relatedServices: ["business-automation", "backend-development"],
        relatedSolutions: ["loan-finance-platforms", "business-management"],
      },
      {
        slug: "erp-development",
        name: "Custom ERP Development",
        shortDescription: "Integrated enterprise resource planning tools unifying finance, inventory, and operations.",
        heroTitle: "Custom ERP & Operations Systems",
        heroSubtitle: "Unify business operations, accounting, inventory, and human resources into a single central source of truth.",
        overview: "We architect cohesive enterprise software that connects distributed operational units, tracks physical assets and financial ledgers, and eliminates departmental data silos.",
        keyFeatures: ["Centralized double-entry ledger integration", "Multi-warehouse inventory tracking", "Purchase order & vendor billing approvals", "Departmental access control & audit trails"],
        technologies: ["TypeScript", "Next.js", "Fastify", "PostgreSQL", "Redis"],
        useCases: ["Manufacturing businesses", "Supply chain operators", "Retail distributors", "Healthcare facilities"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["business-management", "healthcare"],
      },
      {
        slug: "admin-dashboard-development",
        name: "Admin Dashboard Development",
        shortDescription: "High-utility control panels and administrative tooling for data management and analytics.",
        heroTitle: "Administrative Control Panel Engineering",
        heroSubtitle: "Powerful, responsive, and secure administrative dashboards to monitor and control your entire ecosystem.",
        overview: "We design intuitive internal tools and administrative portals that empower executive and support teams to manage database records, moderate content, audit logs, and trigger batch operations.",
        keyFeatures: ["Complex paginated data tables with instant filtering", "Batch CSV/Excel import & validation engines", "Visual analytics & KPI metric widgets", "Granular operator permissions & action audit logs"],
        technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Recharts"],
        useCases: ["Platform operators", "Fintech operations teams", "Content moderation", "Customer support hubs"],
        relatedServices: ["web-application-development", "backend-development"],
        relatedSolutions: ["fintech", "loan-finance-platforms"],
      },
      {
        slug: "custom-web-app-development",
        name: "Custom Web Applications",
        shortDescription: "Bespoke web applications engineered to solve unique and complex operational workflows.",
        heroTitle: "Bespoke Web Application Engineering",
        heroSubtitle: "Custom full-stack software designed specifically around your proprietary business workflows.",
        overview: "When off-the-shelf software fails to meet your exact specifications, we build purpose-built web applications that streamline proprietary operations and deliver distinctive competitive advantages.",
        keyFeatures: ["Custom domain data models & business algorithms", "Interactive client-side calculators & tools", "Third-party API synchronization layers", "Responsive across all desktop and tablet devices"],
        technologies: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL"],
        useCases: ["Specialized service industries", "Proprietary algorithm tools", "Internal operations", "Client self-service portals"],
        relatedServices: ["website-development", "ai-development"],
        relatedSolutions: ["startup-mvp", "business-management"],
      },
    ],
  },
  {
    slug: "mobile-app-development",
    name: "Mobile App Development",
    tag: "Mobile",
    iconName: "Smartphone",
    shortDescription: "Native and cross-platform mobile apps engineered for speed, intuitive UI, and seamless offline sync.",
    heroTitle: "Native & Cross-Platform Mobile Applications",
    heroSubtitle: "High-performance iOS and Android apps engineered with fluid 60fps animations and secure offline sync.",
    overview: "We engineer native and cross-platform mobile applications that delight users with rapid load times, intuitive touch ergonomics, biometric authentication, and resilient offline-first data caching.",
    keyFeatures: [
      "Cross-platform Flutter & React Native development for dual iOS/Android release",
      "Native Android (Kotlin) & iOS (Swift) architectures when hardware performance is critical",
      "Offline-first local SQLite/WatermelonDB storage with cloud reconciliation",
      "Push notification pipelines via Firebase Cloud Messaging (FCM)",
      "Secure biometric login (Fingerprint, FaceID) & encrypted Keychain storage",
      "App Store & Google Play Store release lifecycle management",
    ],
    technologies: ["Flutter", "React Native", "Kotlin", "Swift", "TypeScript", "Firebase", "SQLite", "Node.js"],
    relatedSolutions: ["fintech", "ecommerce", "healthcare", "education"],
    childRoutes: [
      {
        slug: "android-development",
        name: "Android App Development",
        shortDescription: "Native Android apps engineered for maximum hardware optimization and Play Store compliance.",
        heroTitle: "Native Android Application Development",
        heroSubtitle: "Engineered for speed, battery efficiency, and compatibility across thousands of Android device models.",
        overview: "We build native Android applications utilizing modern Kotlin, Jetpack Compose, and Android Architecture Components to deliver responsive and crash-free mobile experiences.",
        keyFeatures: ["Jetpack Compose declarative UI", "Background service & worker synchronization", "Hardware camera, GPS, and sensor integrations", "Google Play Store publishing optimization"],
        technologies: ["Kotlin", "Jetpack Compose", "Android SDK", "Room DB", "Firebase"],
        useCases: ["Field operations", "Consumer mobile apps", "Fintech mobile banking", "Logistics tracking"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["fintech", "loan-finance-platforms"],
      },
      {
        slug: "ios-development",
        name: "iOS App Development",
        shortDescription: "Native iOS applications engineered with Swift, SwiftUI, and Apple Human Interface Guidelines.",
        heroTitle: "Native iOS Application Engineering",
        heroSubtitle: "Crafted for premium Apple device performance, fluid gesture ergonomics, and App Store guidelines.",
        overview: "We create native iOS applications using Swift and SwiftUI, delivering fluid 120Hz animations, Apple Pay integrations, FaceID security, and deep iOS platform integration.",
        keyFeatures: ["SwiftUI modern component architecture", "Apple Pay & in-app purchase integration", "Keychain biometric encryption (FaceID/TouchID)", "App Store review compliance & submission"],
        technologies: ["Swift", "SwiftUI", "CoreData", "Combine", "Apple SDKs"],
        useCases: ["Premium consumer products", "Executive tools", "iOS-exclusive platforms", "Creative media apps"],
        relatedServices: ["backend-development", "mobile-app-development"],
        relatedSolutions: ["ecommerce", "startup-mvp"],
      },
      {
        slug: "flutter-development",
        name: "Flutter App Development",
        shortDescription: "High-performance cross-platform apps built from a single Dart codebase for iOS and Android.",
        heroTitle: "Cross-Platform Flutter Development",
        heroSubtitle: "Ship beautiful iOS and Android apps simultaneously from a unified, high-performance Dart codebase.",
        overview: "Using Google's Flutter framework, we build cross-platform mobile apps with native rendering speeds, identical UI fidelity across platforms, and half the maintenance overhead of dual native codebases.",
        keyFeatures: ["Single unified codebase for iOS and Android", "Skia/Impeller hardware-accelerated 60fps rendering", "Rich custom animations and widget trees", "Fast feature iteration and rapid release cycles"],
        technologies: ["Flutter", "Dart", "Firebase", "BLoC/Riverpod", "REST APIs"],
        useCases: ["Startups & MVPs", "Fintech customer apps", "eCommerce mobile stores", "On-demand services"],
        relatedServices: ["backend-development", "web-application-development"],
        relatedSolutions: ["startup-mvp", "fintech", "ecommerce"],
      },
      {
        slug: "react-native-development",
        name: "React Native Development",
        shortDescription: "Cross-platform mobile applications leveraging modern React ecosystems and native bridging.",
        heroTitle: "React Native Mobile Engineering",
        heroSubtitle: "Leverage the power of React to deliver native mobile experiences across iOS and Android.",
        overview: "We engineer React Native mobile applications that share business logic with web frontends, accelerating feature rollout while preserving native performance and look-and-feel.",
        keyFeatures: ["Shared code across Web and Mobile platforms", "Direct access to native device APIs via bridges", "Over-the-air (OTA) updates via Expo EAS", "Robust offline data caching and synchronization"],
        technologies: ["React Native", "TypeScript", "Expo", "Redux Toolkit", "Node.js"],
        useCases: ["Full-stack digital products", "Community & social platforms", "Enterprise employee apps", "Media apps"],
        relatedServices: ["web-application-development", "backend-development"],
        relatedSolutions: ["education", "startup-mvp"],
      },
    ],
  },
  {
    slug: "ai-development",
    name: "AI Solutions & Integration",
    tag: "AI & ML",
    iconName: "Cpu",
    shortDescription: "Smart AI agents, LLM integrations, automated document extraction, and machine learning workflows.",
    heroTitle: "Applied Artificial Intelligence & Automation",
    heroSubtitle: "Transform manual operational bottlenecks with intelligent AI agents, neural extraction, and LLMs.",
    overview: "We architect and deploy practical, production-ready AI solutions that integrate directly into existing business applications. From automated document OCR and contract analysis to conversational support agents, our AI systems deliver measurable operational efficiency.",
    keyFeatures: [
      "Custom Retrieval-Augmented Generation (RAG) knowledge pipelines",
      "Autonomous multi-step AI agents and decision-making workflows",
      "Automated OCR document parsing for PDF, invoices, and KYC identity verification",
      "Fine-tuned open-source & proprietary LLM models (OpenAI, Anthropic, Gemini, Llama)",
      "Strict data privacy guardrails and token usage cost optimization",
      "Zero-latency semantic search using vector embeddings & pgvector",
    ],
    technologies: ["Python", "FastAPI", "OpenAI API", "Anthropic", "LangChain", "LlamaIndex", "pgvector", "PostgreSQL", "TypeScript"],
    relatedSolutions: ["fintech", "loan-finance-platforms", "business-management", "healthcare"],
    childRoutes: [
      {
        slug: "ai-chatbot-development",
        name: "AI Chatbots & Conversational AI",
        shortDescription: "24/7 intelligent conversational agents with contextual memory and system action triggers.",
        heroTitle: "Conversational AI & Chatbot Engineering",
        heroSubtitle: "Deploy intelligent customer support agents that resolve complex inquiries and trigger backend actions.",
        overview: "Move beyond rigid script-based bots. We build conversational AI systems that understand context, converse fluently in multiple languages, and securely query backend APIs to resolve customer requests autonomously.",
        keyFeatures: ["Contextual multi-turn dialogue memory", "Direct CRM & ticket creation action execution", "WhatsApp, Web & Telegram omnichannel support", "Human agent escalation fallback triggers"],
        technologies: ["TypeScript", "Python", "LangChain", "OpenAI", "WebSockets"],
        useCases: ["Customer support teams", "Lead qualification funnels", "E-commerce order tracking", "Internal HR helpdesks"],
        relatedServices: ["business-automation", "web-application-development"],
        relatedSolutions: ["fintech", "ecommerce"],
      },
      {
        slug: "ai-agent-development",
        name: "Autonomous AI Agents",
        shortDescription: "Multi-step autonomous agents that execute complex multi-tool workflows without human intervention.",
        heroTitle: "Autonomous AI Agent Architecture",
        heroSubtitle: "Deploy autonomous software agents capable of planning, tool execution, and multi-step reasoning.",
        overview: "We architect autonomous AI agent systems that combine planning models, API calling tools, and database access to execute complex business tasks with continuous self-verification.",
        keyFeatures: ["Tool-calling & API execution capabilities", "Loop prevention & self-correcting error recovery", "Structured JSON output validation", "Comprehensive audit logs of agent actions"],
        technologies: ["Python", "LangGraph", "FastAPI", "PostgreSQL", "Redis"],
        useCases: ["Financial reconciliation", "Automated research & reporting", "Data enrichment pipelines", "System monitoring"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["fintech", "business-management"],
      },
      {
        slug: "generative-ai-integration",
        name: "Generative AI Integration",
        shortDescription: "Embed state-of-the-art generative language and vision models into your existing applications.",
        heroTitle: "Generative AI System Integration",
        heroSubtitle: "Seamlessly integrate state-of-the-art generative models directly into your core business software.",
        overview: "We integrate enterprise-grade generative AI capabilities into existing web and mobile applications, enabling intelligent content summarization, personalized generation, and interactive data insights.",
        keyFeatures: ["Secure API proxy layers with token rate limiting", "Prompt template management & versioning", "Streaming response UI integration", "Data anonymization & PII protection"],
        technologies: ["OpenAI", "Anthropic Claude", "Google Gemini", "Next.js", "Fastify"],
        useCases: ["Content drafting platforms", "Contract summarization", "Personalized marketing", "Interactive analytics"],
        relatedServices: ["web-application-development", "ai-development"],
        relatedSolutions: ["education", "business-management"],
      },
      {
        slug: "document-ai",
        name: "Document AI & OCR Extraction",
        shortDescription: "Automate data extraction from invoices, bank statements, PDFs, and identity documents.",
        heroTitle: "Intelligent Document Processing (IDP)",
        heroSubtitle: "Extract structured data from unstructured documents, PDFs, and invoices with 99%+ accuracy.",
        overview: "Eliminate manual data entry with our Document AI pipelines. We combine vision models, OCR engines, and structured JSON parsing to ingest financial statements, government IDs, and invoices instantly.",
        keyFeatures: ["PDF, JPEG & scanned document processing", "Bank statement & salary slip financial extraction", "KYC identity verification (Aadhaar, PAN, Passport)", "Automated anomaly & forgery detection flags"],
        technologies: ["Python", "OpenCV", "Tesseract", "FastAPI", "PostgreSQL"],
        useCases: ["Loan underwriting verification", "Invoice reconciliation", "Insurance claims processing", "KYC onboarding"],
        relatedServices: ["business-automation", "backend-development"],
        relatedSolutions: ["loan-finance-platforms", "fintech"],
      },
      {
        slug: "llm-integration",
        name: "LLM Infrastructure & RAG",
        shortDescription: "Custom Retrieval-Augmented Generation (RAG) pipelines connected to private company knowledge bases.",
        heroTitle: "Enterprise LLM & RAG Infrastructure",
        heroSubtitle: "Connect private corporate documentation with vector search for hallucination-free AI answers.",
        overview: "We architect private RAG pipelines that ground large language models in your organization's internal documentation, technical manuals, and policy databases with verifiable source citations.",
        keyFeatures: ["Chunking & vector embedding pipelines", "High-performance vector database querying (pgvector)", "Strict semantic relevance thresholding", "Zero training on private customer data"],
        technologies: ["pgvector", "PostgreSQL", "LlamaIndex", "Python", "TypeScript"],
        useCases: ["Internal enterprise knowledge bases", "Legal policy search", "Technical documentation Q&A", "Customer support"],
        relatedServices: ["backend-development", "ai-development"],
        relatedSolutions: ["education", "healthcare", "business-management"],
      },
      {
        slug: "ai-automation",
        name: "AI-Powered Business Automation",
        shortDescription: "End-to-end automation pipelines pairing AI decision engines with operational software.",
        heroTitle: "AI-Powered Operational Automation",
        heroSubtitle: "Automate complex decision-making and cross-system data workflows with intelligent AI pipelines.",
        overview: "We bridge AI intelligence with backend automation to replace manual human review loops in lead classification, customer email triaging, and regulatory compliance checks.",
        keyFeatures: ["Intelligent email categorization & automated routing", "Lead scoring & intent classification algorithms", "Cross-system webhook synchronization", "Continuous accuracy metrics monitoring"],
        technologies: ["Python", "Fastify", "PostgreSQL", "Redis", "BullMQ"],
        useCases: ["Inbound email routing", "Sales lead prioritization", "Automated compliance checks", "Content moderation"],
        relatedServices: ["business-automation", "backend-development"],
        relatedSolutions: ["fintech", "business-management"],
      },
    ],
  },
  {
    slug: "backend-development",
    name: "Backend & API Systems",
    tag: "Cloud Backend",
    iconName: "Database",
    shortDescription: "Robust REST & GraphQL APIs, microservices, PostgreSQL/Supabase database schemas, and cloud architecture.",
    heroTitle: "Robust Backend & API Architecture",
    heroSubtitle: "High-throughput, low-latency microservices and database architectures built for scale and security.",
    overview: "We build high-concurrency backend services, high-speed RESTful and GraphQL APIs, and optimized relational database schemas that serve as the indestructible bedrock for web and mobile products.",
    keyFeatures: [
      "High-speed Fastify and Node.js REST API architectures (<20ms response time)",
      "Indexed PostgreSQL database schema design with Prisma ORM",
      "In-memory Redis caching and message queue workers (BullMQ)",
      "JWT authentication, role-based authorization, and rate limiting",
      "Comprehensive OpenAPI/Swagger API documentation",
      "Automated automated database backup, migration, and health monitoring pipelines",
    ],
    technologies: ["Node.js", "Fastify", "TypeScript", "PostgreSQL", "Prisma", "Redis", "Docker", "Linux VPS", "Nginx"],
    relatedSolutions: ["fintech", "loan-finance-platforms", "ecommerce", "business-management"],
    childRoutes: [
      {
        slug: "nodejs-development",
        name: "Node.js & Fastify Backend",
        shortDescription: "High-performance asynchronous server applications engineered with TypeScript and Fastify.",
        heroTitle: "Node.js & Fastify Backend Engineering",
        heroSubtitle: "High-throughput asynchronous backends engineered for low memory footprint and rapid execution.",
        overview: "We specialize in building lean, high-performance Node.js backend systems using Fastify and TypeScript, handling thousands of concurrent requests per second with sub-millisecond route resolution.",
        keyFeatures: ["Schema-based fast JSON serialization", "Asynchronous non-blocking I/O architecture", "Structured logging with Pino", "Modular plugin-based route encapsulation"],
        technologies: ["Node.js", "Fastify", "TypeScript", "Pino", "Prisma"],
        useCases: ["High-traffic API gateways", "Real-time chat backends", "Microservices", "Data ingestion engines"],
        relatedServices: ["backend-development", "web-application-development"],
        relatedSolutions: ["fintech", "startup-mvp"],
      },
      {
        slug: "rest-api-development",
        name: "REST API Engineering",
        shortDescription: "Clean, standardized RESTful web services with OpenAPI specifications and robust versioning.",
        heroTitle: "Scalable REST API Architecture",
        heroSubtitle: "Predictable, well-documented, and secure RESTful endpoints designed for third-party developer consumption.",
        overview: "We design RESTful APIs conforming to industry-standard HTTP conventions, strict JSON payload validation, standardized pagination schemes, and comprehensive error schemas.",
        keyFeatures: ["OpenAPI 3.0 / Swagger documentation", "Idempotent write operations & request deduplication", "Token-bucket rate limiting & DDoS mitigation", "Semantic HTTP response codes & uniform error payloads"],
        technologies: ["Fastify", "TypeScript", "Zod", "OpenAPI", "PostgreSQL"],
        useCases: ["Public developer APIs", "Mobile app backend integration", "Partner data exchange", "SaaS integrations"],
        relatedServices: ["web-application-development", "mobile-app-development"],
        relatedSolutions: ["fintech", "ecommerce"],
      },
      {
        slug: "graphql-development",
        name: "GraphQL API Architecture",
        shortDescription: "Flexible, strongly typed GraphQL APIs eliminating over-fetching and consolidating multiple endpoints.",
        heroTitle: "GraphQL API Development",
        heroSubtitle: "Query exactly what you need in a single round-trip with strongly typed GraphQL schemas.",
        overview: "We build GraphQL APIs that unify distributed database queries and microservices into a single cohesive graph, empowering frontend developers with flexible data querying without backend changes.",
        keyFeatures: ["Strongly typed schema definitions & code generation", "DataLoader batching resolving N+1 query bottlenecks", "Real-time subscriptions via WebSockets", "Granular field-level authorization"],
        technologies: ["GraphQL", "Apollo Server", "Node.js", "TypeScript", "PostgreSQL"],
        useCases: ["Complex dashboard applications", "Multi-platform client applications", "Rapid frontend iteration", "E-commerce catalogs"],
        relatedServices: ["web-application-development", "backend-development"],
        relatedSolutions: ["ecommerce", "startup-mvp"],
      },
      {
        slug: "postgresql-development",
        name: "PostgreSQL Database Architecture",
        shortDescription: "High-performance relational database design, query optimization, indexing, and data modeling.",
        heroTitle: "PostgreSQL Schema Design & Optimization",
        heroSubtitle: "Engineered for bulletproof relational integrity, optimized indexes, and sub-millisecond query execution.",
        overview: "We design normalized, highly indexed PostgreSQL database architectures capable of handling complex joins, JSONB unstructured data, full-text search, and high transactional concurrency without slowdowns.",
        keyFeatures: ["Custom composite B-Tree, GIN, and GiST indexes", "ACID transactional guarantees with foreign key integrity", "Complex aggregation queries & materialized views", "Automated migration pipelines via Prisma"],
        technologies: ["PostgreSQL", "Prisma ORM", "SQL", "pgvector", "Redis"],
        useCases: ["Financial transaction ledgers", "Multi-million row catalog indexing", "Enterprise CRM/ERP databases", "Analytical stores"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["fintech", "loan-finance-platforms"],
      },
      {
        slug: "cloud-backend-development",
        name: "Cloud & Microservices Infrastructure",
        shortDescription: "Containerized cloud infrastructure, reverse proxies, and VPS server deployment architecture.",
        heroTitle: "Cloud Infrastructure & Server Architecture",
        heroSubtitle: "Resilient VPS, Docker containerization, and reverse proxy architectures ensuring 99.9% uptime.",
        overview: "We configure, harden, and manage cloud VPS infrastructure, Nginx reverse proxies, Docker container orchestration, and automated deployment pipelines that keep your services running continuously.",
        keyFeatures: ["Dockerized multi-container orchestration", "Nginx SSL termination & reverse proxy load balancing", "Automated PM2 process management & zero-downtime restarts", "VPS firewall hardening (UFW, fail2ban)"],
        technologies: ["Docker", "Nginx", "Linux VPS", "PM2", "GitHub Actions", "Cloudflare"],
        useCases: ["Self-hosted enterprise platforms", "Cost-effective cloud hosting", "High-security internal backends", "Scalable microservices"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["business-management", "fintech"],
      },
    ],
  },
  {
    slug: "business-automation",
    name: "Business Automation",
    tag: "Automation",
    iconName: "Zap",
    shortDescription: "Custom internal tools, workflow automation engines, CRM/ERP integrations, and data pipelines.",
    heroTitle: "End-to-End Business Process Automation",
    heroSubtitle: "Eliminate repetitive manual tasks and accelerate operational throughput with custom automation engines.",
    overview: "We engineer custom automation pipelines that seamlessly connect disparate software systems, sync databases in real time, automate document generation, and trigger instant business notifications.",
    keyFeatures: [
      "Automated cross-platform webhook listeners and event dispatchers",
      "Scheduled background cron processing for recurring reports & reconciliation",
      "Instant WhatsApp Business & transactional email notification triggers",
      "Automated spreadsheet ingestion, validation, and database synchronization",
      "Third-party API synchronization with payment gateways, CRMs, and accounting tools",
      "Zero-downtime queue workers powered by Redis & BullMQ",
    ],
    technologies: ["Node.js", "TypeScript", "Python", "Redis", "BullMQ", "PostgreSQL", "Fastify", "Webhooks"],
    relatedSolutions: ["loan-finance-platforms", "fintech", "business-management", "ecommerce"],
    childRoutes: [
      {
        slug: "workflow-automation",
        name: "Workflow Automation Engines",
        shortDescription: "Custom multi-step business workflow engines executing sequential operational actions.",
        heroTitle: "Custom Workflow Automation Engines",
        heroSubtitle: "Automate complex multi-step approvals, assignments, and notifications with zero human delay.",
        overview: "We build custom workflow automation state machines that guide business processes from initiation to completion, ensuring every department executes tasks in sequence with zero lost communications.",
        keyFeatures: ["Custom state-machine business rule validation", "Automated multi-level managerial approval chains", "Conditional branching based on real-time business data", "Real-time task SLA breach alerts"],
        technologies: ["TypeScript", "Node.js", "PostgreSQL", "Redis", "BullMQ"],
        useCases: ["Credit approval workflows", "Employee onboarding", "Procurement requests", "Service ticket escalation"],
        relatedServices: ["business-automation", "web-application-development"],
        relatedSolutions: ["loan-finance-platforms", "business-management"],
      },
      {
        slug: "crm-automation",
        name: "CRM & Sales Pipeline Automation",
        shortDescription: "Automate lead capture, scoring, executive assignment, and follow-up messaging.",
        heroTitle: "CRM & Lead Automation Engineering",
        heroSubtitle: "Capture, enrich, score, and distribute sales leads to executives instantly in under 1 second.",
        overview: "Turn inbound website traffic and ad leads into closed deals faster. Our CRM automation engines ingest leads from web forms, ads, and landing pages, assign them based on agent availability, and send instant welcome messages.",
        keyFeatures: ["Sub-second lead ingestion & round-robin assignment", "Instant WhatsApp & SMS welcome triggers", "Automated executive follow-up reminders", "Lead activity audit logs and conversion tracking"],
        technologies: ["Node.js", "TypeScript", "PostgreSQL", "WhatsApp API", "Fastify"],
        useCases: ["Loan & finance brokerages", "Real estate sales teams", "Insurance agencies", "High-velocity sales"],
        relatedServices: ["web-application-development", "business-automation"],
        relatedSolutions: ["loan-finance-platforms", "fintech"],
      },
      {
        slug: "erp-automation",
        name: "ERP & Inventory Synchronization",
        shortDescription: "Synchronize inventory, sales orders, invoices, and accounting ledgers across platforms.",
        heroTitle: "ERP & Operational Synchronization",
        heroSubtitle: "Bridge accounting, inventory, and order systems into a unified real-time data sync pipeline.",
        overview: "Eliminate manual double-entry. We build bidirectional synchronization pipelines between your custom software and third-party accounting, billing, and warehouse management tools.",
        keyFeatures: ["Real-time inventory level reconciliation", "Automated invoice generation & PDF dispatch", "Payment settlement ledger matching", "Conflict resolution algorithms for concurrent updates"],
        technologies: ["TypeScript", "Node.js", "PostgreSQL", "Redis", "Fastify"],
        useCases: ["Multi-channel retail", "Manufacturing supply chains", "Distribution networks", "E-commerce operations"],
        relatedServices: ["backend-development", "business-automation"],
        relatedSolutions: ["business-management", "ecommerce"],
      },
      {
        slug: "data-automation",
        name: "Batch Data & Spreadsheet Automation",
        shortDescription: "Automate large-scale CSV/Excel data ingestion, cleaning, validation, and database updates.",
        heroTitle: "Batch Data Ingestion & ETL Automation",
        heroSubtitle: "Process, clean, validate, and load hundreds of thousands of spreadsheet records in seconds.",
        overview: "Stop wrestling with messy Excel files. We engineer streaming batch ETL pipelines that parse large spreadsheets, identify duplicates, match fuzzy naming anomalies, and upsert records into PostgreSQL effortlessly.",
        keyFeatures: ["High-speed stream parsing for 100k+ row spreadsheets", "AI-assisted column header auto-mapping", "Row-by-row validation error logging with visual correction", "One-click rollback and transaction safety"],
        technologies: ["TypeScript", "Node.js", "PostgreSQL", "Prisma", "BullMQ"],
        useCases: ["Bank pincode list updates", "Company master classification", "Price list updates", "Catalog imports"],
        relatedServices: ["backend-development", "ai-development"],
        relatedSolutions: ["fintech", "loan-finance-platforms"],
      },
      {
        slug: "api-automation",
        name: "Third-Party API Integrations",
        shortDescription: "Connect payment gateways, KYC APIs, messaging providers, and external web services.",
        heroTitle: "Third-Party API & Webhook Integration",
        heroSubtitle: "Securely connect your software with banking gateways, KYC verification APIs, and messaging channels.",
        overview: "We integrate enterprise external APIs with resilient error handling, retry queues, webhook signature validation, and secure credential vaulting.",
        keyFeatures: ["Payment gateway webhooks (Stripe, Razorpay, Cashfree)", "Government KYC identity verification APIs (PAN, GSTIN, Aadhaar)", "Transactional messaging (WhatsApp, SMS, SendGrid)", "Automated retry backoff & dead-letter queues"],
        technologies: ["Node.js", "TypeScript", "Fastify", "Redis", "Crypto"],
        useCases: ["Payment processing", "Instant customer identity verification", "Multi-channel alerts", "Banking integrations"],
        relatedServices: ["backend-development", "web-application-development"],
        relatedSolutions: ["fintech", "loan-finance-platforms"],
      },
    ],
  },
];

// ─── 7 INDUSTRY SOLUTIONS ─────────────────────────────────────────────────────

export const SOLUTIONS_CONFIG: IndustrySolution[] = [
  {
    slug: "fintech",
    name: "Fintech Platforms & Financial Software",
    badge: "Fintech",
    shortDescription: "Secure, compliant, and scalable digital architectures for financial technology platforms.",
    heroTitle: "Enterprise Fintech Software & Platforms",
    heroSubtitle: "Engineered for strict regulatory compliance, low-latency transaction processing, and bank-grade security.",
    overview: "We architect end-to-end fintech solutions that bridge consumer-facing financial applications with complex banking APIs, credit rule engines, and automated underwriting pipelines.",
    challengesSolved: [
      "Fragmented banking partner policies and inconsistent manual approval guidelines",
      "High latency in customer identity verification and credit eligibility scoring",
      "Data security risks and strict regulatory compliance requirements",
      "Manual data entry errors during bulk financial spreadsheet reconciliation",
    ],
    coreCapabilities: [
      "Bank & NBFC policy categorization and tiering matrix engines",
      "Sub-second pincode serviceability and branch coverage validation",
      "Secure payment gateway integrations and digital ledger bookkeeping",
      "Automated KYC document extraction (PAN, Aadhaar, Bank Statement OCR)",
    ],
    technologies: ["Next.js", "Fastify", "PostgreSQL", "Prisma", "Redis", "Docker", "Python", "Tailwind CSS"],
    connectedServices: [
      { name: "Web Application Development", href: "/services/web-application-development" },
      { name: "Backend & API Systems", href: "/services/backend-development" },
      { name: "AI Solutions & OCR", href: "/services/ai-development" },
      { name: "Business Automation", href: "/services/business-automation" },
      { name: "Finance Tools & Calculators", href: "/finance-tools" },
    ],
  },
  {
    slug: "loan-finance-platforms",
    name: "Loan & Lending Operations Systems",
    badge: "Lending Systems",
    shortDescription: "Complete loan origination, policy checking, and lead management systems for loan distributors and DSA teams.",
    heroTitle: "Loan Origination & Distribution Systems",
    heroSubtitle: "Automate loan distribution, multi-lender company checking, and customer lead lifecycles.",
    overview: "Our lending software solutions empower financial distributors, DSAs, and loan brokers to verify company eligibility across 10+ major banks simultaneously, check branch serviceability, and track leads through credit disbursement.",
    challengesSolved: [
      "Wasting hours manually checking multiple bank company category lists",
      "Leads getting rejected due to non-serviceable pincodes or negative areas",
      "Unassigned leads falling through the cracks without executive follow-up",
      "Lack of real-time visibility into loan pipeline conversion metrics",
    ],
    coreCapabilities: [
      "Multi-lender instant company category comparison (CAT A, CAT B, Superprime)",
      "Pan-India 19,500+ Pincode serviceability lookup with auto-enrichment",
      "Automated lead ingestion, round-robin assignment, and executive reminders",
      "Interactive loan EMI calculation and amortization table breakdowns",
    ],
    technologies: ["React", "Next.js", "Fastify", "PostgreSQL", "Prisma", "Tailwind CSS"],
    connectedServices: [
      { name: "Company Category Check", href: "/company-check" },
      { name: "Pincode Eligibility Checker", href: "/pincode-check" },
      { name: "Custom CRM Development", href: "/services/web-application-development/crm-development" },
      { name: "Data Ingestion Automation", href: "/services/business-automation/data-automation" },
    ],
  },
  {
    slug: "business-management",
    name: "Business Management & Operations Systems",
    badge: "Enterprise Ops",
    shortDescription: "Custom ERP, CRM, and internal tooling designed to consolidate distributed business workflows.",
    heroTitle: "Custom Business Management & Operations Software",
    heroSubtitle: "Replace disconnected spreadsheets with centralized, real-time enterprise management systems.",
    overview: "We engineer bespoke operational software that unites inventory tracking, customer relationships, staff task allocations, and financial reporting into an intuitive centralized portal.",
    challengesSolved: [
      "Fragmented data scattered across disconnected Excel sheets and messaging apps",
      "Expensive recurring monthly subscription fees for rigid off-the-shelf software",
      "Lack of operational transparency across branch offices and teams",
      "Human errors during manual invoice and inventory updating",
    ],
    coreCapabilities: [
      "Custom role-based permissions for managers, executives, and viewers",
      "Centralized customer timeline and communication history logging",
      "Real-time operational KPI dashboards and exportable financial reports",
      "Automated task reminders, status transitions, and audit logs",
    ],
    technologies: ["Next.js", "TypeScript", "Fastify", "PostgreSQL", "Redis", "Tailwind CSS"],
    connectedServices: [
      { name: "Custom ERP Development", href: "/services/web-application-development/erp-development" },
      { name: "Custom CRM Development", href: "/services/web-application-development/crm-development" },
      { name: "Admin Dashboard Development", href: "/services/web-application-development/admin-dashboard-development" },
      { name: "Workflow Automation", href: "/services/business-automation/workflow-automation" },
    ],
  },
  {
    slug: "ecommerce",
    name: "Modern eCommerce & Direct-to-Consumer (D2C)",
    badge: "eCommerce",
    shortDescription: "Fast, high-converting digital storefronts and scalable multi-vendor marketplaces.",
    heroTitle: "Modern eCommerce & Digital Storefront Engineering",
    heroSubtitle: "Engineered for blazing fast catalog browsing, frictionless checkouts, and high customer retention.",
    overview: "We design and engineer bespoke eCommerce experiences with lightning-fast catalog search, dynamic cart state management, automated shipping API integrations, and secure payment processing.",
    challengesSolved: [
      "High bounce rates caused by slow product page load times (>3 seconds)",
      "Cart abandonment triggered by clunky, multi-step checkout processes",
      "Inventory sync mismatches across warehouse and online store",
      "Inability to customize checkout flows on closed-source platform builders",
    ],
    coreCapabilities: [
      "Sub-second headless product catalog with instant client-side filtering",
      "One-page optimized checkout flow integrated with domestic & global gateways",
      "Automated order fulfillment webhooks & tracking notifications",
      "Customer loyalty, coupon engine, and dynamic discount architectures",
    ],
    technologies: ["Next.js", "React", "Node.js", "PostgreSQL", "Tailwind CSS", "Stripe API"],
    connectedServices: [
      { name: "eCommerce Websites", href: "/services/website-development/ecommerce-websites" },
      { name: "Mobile App Development", href: "/services/mobile-app-development" },
      { name: "Payment API Integrations", href: "/services/business-automation/api-automation" },
    ],
  },
  {
    slug: "education",
    name: "EdTech & Learning Management Systems",
    badge: "EdTech",
    shortDescription: "Interactive learning platforms, student portals, course delivery systems, and assessment tools.",
    heroTitle: "EdTech & Learning Management Platforms",
    heroSubtitle: "Deliver engaging digital learning experiences with video streaming, student tracking, and automated tests.",
    overview: "We engineer scalable educational portals and learning management systems (LMS) with secure video content delivery, automated grading engines, student progress dashboards, and live interactive features.",
    challengesSolved: [
      "Unsecured video content vulnerable to unauthorized downloading and piracy",
      "Manual grading overhead for high-volume student test submissions",
      "Clunky user interfaces reducing student course completion rates",
      "Lack of granular analytics tracking individual student engagement",
    ],
    coreCapabilities: [
      "Encrypted adaptive bitrate video streaming with DRM protection",
      "Interactive quizzes, automated grading algorithms, and certificate generation",
      "Student progress analytics and teacher grading management portals",
      "Live chat, discussion forums, and announcement notifications",
    ],
    technologies: ["Next.js", "React", "Node.js", "PostgreSQL", "AWS S3/CloudFront", "Tailwind CSS"],
    connectedServices: [
      { name: "Web Application Development", href: "/services/web-application-development" },
      { name: "Mobile App Development", href: "/services/mobile-app-development" },
      { name: "AI Learning Assistants", href: "/services/ai-development/llm-integration" },
    ],
  },
  {
    slug: "healthcare",
    name: "Healthcare & Telemedicine Systems",
    badge: "Healthcare",
    shortDescription: "HIPAA/privacy-conscious patient portals, doctor appointment scheduling, and electronic records.",
    heroTitle: "Healthcare & Digital Health Solutions",
    heroSubtitle: "Secure, reliable, and compliant digital health platforms for clinics, doctors, and patient care.",
    overview: "We architect secure healthcare applications with patient appointment booking, teleconsultation video rooms, digital prescription generation, and encrypted medical record management.",
    challengesSolved: [
      "Inefficient patient scheduling leading to long clinic wait times and no-shows",
      "Scattered paper medical records vulnerable to loss and confidentiality breaches",
      "Lack of accessible digital follow-up channels between doctors and patients",
      "Strict data privacy regulations requiring end-to-end encryption",
    ],
    coreCapabilities: [
      "Real-time doctor calendar slot booking with automated SMS/WhatsApp reminders",
      "Encrypted Electronic Health Record (EHR) storage with strict access logs",
      "Integrated WebRTC video consultation rooms with digital prescription drafting",
      "Secure patient self-service portal for lab reports and billing history",
    ],
    technologies: ["React", "Next.js", "Fastify", "PostgreSQL", "WebRTC", "Tailwind CSS"],
    connectedServices: [
      { name: "Web Application Development", href: "/services/web-application-development" },
      { name: "Mobile App Development", href: "/services/mobile-app-development" },
      { name: "Document AI & Extraction", href: "/services/ai-development/document-ai" },
    ],
  },
  {
    slug: "startup-mvp",
    name: "Startup MVP & Rapid Product Launch",
    badge: "Startups",
    shortDescription: "Fast-track Minimum Viable Product (MVP) engineering designed to validate ideas and raise capital in 4-6 weeks.",
    heroTitle: "Startup MVP Engineering & Rapid Launch",
    heroSubtitle: "Turn your visionary concept into a production-ready software product in 4 to 6 weeks.",
    overview: "We partner with ambitious startup founders to design, build, and deploy production-ready Minimum Viable Products (MVPs) with clean scalable architectures that impress users and investors alike.",
    challengesSolved: [
      "Long development cycles delaying market validation and draining runway",
      "Low-quality outsourced code that requires complete rewriting when scaling",
      "Unfocused feature bloat distracting from core product value propositions",
      "Lack of technical leadership to architect scalable cloud databases",
    ],
    coreCapabilities: [
      "Rapid UI/UX wireframing and interactive design prototype validation",
      "Full-stack web & cross-platform mobile development ready for real users",
      "Integrated authentication, billing, analytics, and error tracking",
      "Investor-ready technical architecture documentation and clean codebase handover",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Fastify", "PostgreSQL", "Tailwind CSS", "Vercel"],
    connectedServices: [
      { name: "Web Application Development", href: "/services/web-application-development" },
      { name: "Mobile App Development", href: "/services/mobile-app-development" },
      { name: "AI Solutions & Integration", href: "/services/ai-development" },
      { name: "High-Converting Landing Pages", href: "/services/website-development/landing-pages" },
    ],
  },
];

// ─── 7 FINANCE CALCULATORS CONFIG ─────────────────────────────────────────────

export const FINANCE_TOOLS_CONFIG: FinanceToolItem[] = [
  {
    slug: "emi-calculator",
    name: "Standard Loan EMI Calculator",
    badge: "Interactive",
    description: "Calculate monthly installment, total interest payable, and amortization schedule for any loan amount.",
    heroTitle: "Loan EMI Calculator & Amortization Engine",
    heroSubtitle: "Plan your borrowing with precision. Calculate exact monthly EMI, total interest, and annual breakdown.",
    formulaDescription: "EMI = [P x R x (1+R)^N] / [(1+R)^N - 1], where P is Principal, R is monthly interest rate, and N is tenure in months.",
    keyBenefits: [
      "Instant real-time calculation with interactive sliders",
      "Visual principal vs interest distribution breakdown chart",
      "Month-by-month and year-by-year amortization schedule table",
      "Prepayment impact simulator showing interest saved",
    ],
  },
  {
    slug: "personal-loan-emi-calculator",
    name: "Personal Loan EMI Calculator",
    badge: "Personal Loans",
    description: "Calculate monthly installments for unsecured personal loans across tenures from 1 to 7 years.",
    heroTitle: "Personal Loan EMI Calculator",
    heroSubtitle: "Accurately compute monthly installments and total borrowing costs for unsecured personal loans.",
    formulaDescription: "Calculates reducing-balance EMI tailored for typical personal loan interest brackets (10.5% to 24% p.a.).",
    keyBenefits: [
      "Tailored for short to medium tenure borrowings (12 to 84 months)",
      "Helps determine affordable monthly payout before applying",
      "Compare interest variations between fixed and floating bank rates",
      "Check company category eligibility across top partner banks",
    ],
  },
  {
    slug: "home-loan-emi-calculator",
    name: "Home Loan EMI Calculator",
    badge: "Home Loans",
    description: "Plan long-term home loan installments with loan tenures up to 30 years and tax benefit estimates.",
    heroTitle: "Home Loan EMI Calculator",
    heroSubtitle: "Plan your dream home financing with long-term tenure breakdowns and amortization projections.",
    formulaDescription: "Engineered for 10 to 30-year mortgage repayment cycles with reducing balance interest calculations.",
    keyBenefits: [
      "Optimized for high principal amounts and long tenures up to 30 years",
      "Clear visualization of early-year interest dominance vs principal growth",
      "Estimate annual tax deductions under Section 80C and Section 24b",
      "Part-prepayment calculation to shorten loan tenure by years",
    ],
  },
  {
    slug: "business-loan-emi-calculator",
    name: "Business Loan EMI Calculator",
    badge: "Business Loans",
    description: "Estimate monthly working capital and machinery term loan installments for commercial enterprises.",
    heroTitle: "Business Loan EMI Calculator",
    heroSubtitle: "Calculate financing costs for business expansion, equipment purchases, and working capital lines.",
    formulaDescription: "Calculates standard commercial term loan schedules with flexible tenure and rate configurations.",
    keyBenefits: [
      "Evaluate operational cash flow requirements before acquiring debt",
      "Supports flexible business loan tenures from 1 to 10 years",
      "Assess total interest cost impact on company profit margins",
      "Verify company categorization status with major institutional lenders",
    ],
  },
  {
    slug: "loan-eligibility-calculator",
    name: "Loan Eligibility Calculator",
    badge: "Eligibility",
    description: "Estimate maximum eligible loan amount based on net monthly salary, existing EMIs, and FOIR guidelines.",
    heroTitle: "Loan Eligibility & Borrowing Power Calculator",
    heroSubtitle: "Determine the maximum loan amount banks will approve based on your monthly income and current obligations.",
    formulaDescription: "Uses standard Fixed Obligation to Income Ratio (FOIR 40% - 65%) according to bank underwriting norms.",
    keyBenefits: [
      "Estimates realistic approval ceilings before filing applications",
      "Incorporates existing credit card & personal loan obligations",
      "Shows impact of adding a co-applicant to increase borrowing capacity",
      "Instant integration with bank-specific category policy guidelines",
    ],
  },
  {
    slug: "interest-calculator",
    name: "Simple & Compound Interest Calculator",
    badge: "Interest Engine",
    description: "Compare total interest payouts across simple interest and multi-frequency compounding periods.",
    heroTitle: "Interest Rate & Growth Calculator",
    heroSubtitle: "Compare total interest generation and growth across simple and compound interest compounding periods.",
    formulaDescription: "Computes Simple Interest (P x R x T) and Compound Interest (P(1 + r/n)^(nt)) for monthly, quarterly, and annual compounding.",
    keyBenefits: [
      "Side-by-side comparison of simple vs compound growth over time",
      "Custom compounding intervals: Monthly, Quarterly, Half-Yearly, Annually",
      "Visual wealth accumulation curve",
      "Clear breakdown of net returns after inflation adjustments",
    ],
  },
  {
    slug: "loan-tenure-calculator",
    name: "Loan Tenure & Payoff Calculator",
    badge: "Tenure Planner",
    description: "Discover how increasing your monthly payment reduces your total loan tenure and saves thousands in interest.",
    heroTitle: "Loan Tenure & Payoff Calculator",
    heroSubtitle: "Calculate the exact timeline to become debt-free by adjusting your monthly installment amount.",
    formulaDescription: "Calculates the exact number of months required to extinguish a debt given a fixed monthly payment and interest rate.",
    keyBenefits: [
      "Calculate the exact payoff date under different repayment amounts",
      "See how an extra Rs. 2,000/month cuts years off your loan tenure",
      "Calculate total cumulative interest saved by aggressive repayment",
      "Plan early debt freedom with customized step-up payments",
    ],
  },
];
